name: police_com
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flex_color_scheme: ^8.4.0
  shared_preferences: ^2.5.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  toastification: ^3.0.2
  animated_theme_switcher: ^2.0.10
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  http: ^1.3.0
  dio: ^5.8.0+1
  riverpod_annotation: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  path: any
  flutter_launcher_icons: ^0.14.4
  mobile_scanner: ^7.0.1
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.3.2
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
